[package]
name = "wmproxy"
version = "0.1.1"
edition = "2021"
authors = [ "tickbh <tickdream125@hotmail.com>" ]
description = " http https proxy by rust"
repository = "https://github.com/tickbh/qyproxy"
license = "Apache-2.0"
keywords = ["http"]

[dependencies]

tokio = { version = "1", features = [
    "net",
    "fs",
    "macros",
    "io-std",
    "io-util",
    "rt",
    "rt-multi-thread", # so examples can use #[tokio::main]
    "sync",
    "time",
    "test-util",
] }
commander = "0.1.3"
forever-rs = { version = "0.1.0" }
log = "0.4.19"
bitflags="2.4"

tokio-util = "0.7"
rustls = { version = "0.21.7", default-features = false }
webpki-roots = "0.25"
rustls-pemfile = "1.0.3"
webpki = { version = "0.22", features = ["alloc", "std"] }
tokio-rustls="0.24"
futures-core = { version = "0.3", default-features = false }

# webparse = { version = "0.1.2"}

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[dependencies.webparse]
path = "../webparse"
