[package]
name = "qyproxy"
version = "0.1.0"
edition = "2021"
authors = [ "tickbh <tickdream125@hotmail.com>" ]
description = "a web parse"
repository = "https://github.com/tickbh/qyproxy"
license = "Apache-2.0"
keywords = []

[dependencies]

tokio = { version = "1", features = [
    "fs",
    "macros",
    "io-std",
    "io-util",
    "rt",
    "rt-multi-thread", # so examples can use #[tokio::main]
    "sync",
    "time",
    "test-util",
] }
hyper = { version="0.14", features=[
    "client",
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
]}

http = "0.2"
http-body = "0.4"
httpdate = "1.0"
httparse = "1.6"
commander = "0.1.3"
forever-rs = { version = "0.1.0" }
log = "0.4.19"

[dependencies.webparse]
path = "../webparse"
