
server: 127.0.0.1:8091
center: true
ts: true

mappings:
  - name: web
    mode: http
    local_addr: 127.0.0.1:8080
    domain: localhost
  - name: web1
    mode: http
    local_addr: 127.0.0.1:8080
    domain: localhost1
  - name: web2
    mode: tcp
    local_addr: 127.0.0.1:8080
    domain: 