bind_addr = "0.0.0.0:8090"

[reverse.file_server]
root = ""
prefix = "/root"
hide = [".git"]
index = []

[http]
aa = "b"
[[http.server]]
bind_addr = "127.0.0.1:81"
server_name = "localhost"
root="E:/"

[[http.server.upstream]]
name = "server"

server = [
  {addr="127.0.0.1:8080", fail_timeout=30},
  {addr="127.0.0.1:8081"}
]

[[http.server.location]]
rule = "/root"
file_server = { browse = true }
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]

[[http.server.location]]
rule = "/"
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]
# reverse_proxy = "https://www.baidu.com"
reverse_proxy = "http://server"
headers = [
  ["+", "aaa", "bbb"]
]
# reverse_proxy = "http://192.168.17.22:8080"


# [http.server.location.file_server]
# root = "D:/"

# [[server]]
# listen = 81
# server_name = "localhost"