[proxy]
bind_addr = "0.0.0.0:8090"
flag = 7

[http]
aa = "b"

[[http.upstream]]
name = "server"
server = [
  {addr="127.0.0.1:8080", fail_timeout=30},
  # {addr="127.0.0.1:8081"}
]

[[http.server]]
bind_addr = "0.0.0.0:81"
server_name = "soft.wm-proxy.com"
root="E:/"
cert="key/soft.wm-proxy.com.pem"
key="key/soft.wm-proxy.com.key"
headers = [
  ["proxy", "x-forward-for", "$client_ip"],
  ["+", "last-modified", "from proxy"]
]

[[http.server.location]]
rule = "/root"
file_server = { browse = true }
proxy_pass = ""

[[http.server.location]]
rule = "/"
method = "get"
reverse_proxy = "http://server"
headers = [
  ["+", "aaa", "bbb"]
]


# [[http.server]]
# bind_addr = "0.0.0.0:81"
# server_name = "local.tool.fit"
# root="E:/1"
# cert="key/local.tool.fit.pem"
# key="key/local.tool.fit.key"


# [[http.server.location]]
# rule = "/root"
# file_server = { browse = true }

# [[http.server.location]]
# rule = "/"
# reverse_proxy = "https://www.baidu.com"
# headers = [
#   ["+", "aaa", "bbb"]
# ]