bind_addr = "0.0.0.0:8090"

[reverse.file_server]
root = ""
prefix = "/root"
hide = [".git"]
index = []

[http]
aa = "b"

[[http.server]]
bind_addr = "127.0.0.1:81"
server_name = "soft.wm-proxy.com"
root="E:/"
cert="key/soft.wm-proxy.com.pem"
key="key/soft.wm-proxy.com.key"

[[http.server.upstream]]
name = "server"

server = [
  {addr="127.0.0.1:8080", fail_timeout=30},
  {addr="127.0.0.1:8081"}
]

[[http.server.location]]
rule = "/root"
file_server = { browse = true }
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]

[[http.server.location]]
rule = "/"
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]
reverse_proxy = "http://server"
headers = [
  ["+", "aaa", "bbb"]
]


[[http.server]]
bind_addr = "127.0.0.1:81"
server_name = "local.tool.fit"
root="E:/1"
cert="key/local.tool.fit.pem"
key="key/local.tool.fit.key"


[[http.server.upstream]]
name = "server"

server = [
  {addr="127.0.0.1:8080", fail_timeout=30},
  {addr="127.0.0.1:8081"}
] 

[[http.server.location]]
rule = "/root"
file_server = { browse = true }
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]

[[http.server.location]]
rule = "/"
proxy_pass = ""
set_header = { HOST= "$host", X-Real-IP= "$remote_addr" }
set = [
  { name= "Hammer", sku= 738594937 }
]
reverse_proxy = "https://www.baidu.com"
headers = [
  ["+", "aaa", "bbb"]
]